var searchData=
[
  ['f_0',['f',['../commands.html#cmdfrndopen',1,'\\f('],['../commands.html#cmdfrndclose',1,'\\f)'],['../commands.html#cmdfbropen',1,'\\f['],['../commands.html#cmdfbrclose',1,'\\f]'],['../commands.html#cmdfcurlyclose',1,'\\f}']]],
  ['f_20environment_1',['\\f{environment}{',['../commands.html#cmdfcurlyopen',1,'']]],
  ['f_24_2',['\\f$',['../commands.html#cmdfdollar',1,'']]],
  ['favorite_20programming_20language_20is_20x_20can_20i_20still_20use_20doxygen_3',['My favorite programming language is X. Can I still use Doxygen?',['../faq.html#faq_pgm_X',1,'']]],
  ['features_4',['Features',['../features.html',1,'']]],
  ['fenced_20code_20blocks_5',['Fenced Code Blocks',['../markdown.html#md_fenced',1,'']]],
  ['file_6',['file',['../starting.html#step1',1,'Step 1: Creating a configuration file'],['../faq.html#faq_html_header',1,'The overall HTML output looks different, while I only wanted to use my own html header file']]],
  ['file_20caption_20sizeindication_20size_7',['file caption sizeindication size',['../commands.html#cmddiafile',1,'\\diafile \&lt;file\&gt; [&quot;caption&quot;] [\&lt;sizeindication\&gt;=\&lt;size\&gt;]'],['../commands.html#cmddotfile',1,'\\dotfile \&lt;file\&gt; [&quot;caption&quot;] [\&lt;sizeindication\&gt;=\&lt;size\&gt;]'],['../commands.html#cmdimage',1,'\\image[&apos;{&apos;option[,option]&apos;}&apos;] \&lt;format\&gt; \&lt;file\&gt; [&quot;caption&quot;] [\&lt;sizeindication\&gt;=\&lt;size\&gt;]'],['../commands.html#cmdmscfile',1,'\\mscfile \&lt;file\&gt; [&quot;caption&quot;] [\&lt;sizeindication\&gt;=\&lt;size\&gt;]']]],
  ['file_20header_20name_8',['file header name',['../commands.html#cmdcategory',1,'\\category \&lt;name\&gt; [\&lt;header-file\&gt;] [\&lt;header-name\&gt;]'],['../commands.html#cmdclass',1,'\\class \&lt;name\&gt; [\&lt;header-file\&gt;] [\&lt;header-name\&gt;]'],['../commands.html#cmdheaderfile',1,'\\headerfile &lt;header-file&gt; [&lt;header-name&gt;]'],['../commands.html#cmdinterface',1,'\\interface \&lt;name\&gt; [\&lt;header-file\&gt;] [\&lt;header-name\&gt;]'],['../commands.html#cmdprotocol',1,'\\protocol \&lt;name\&gt; [\&lt;header-file\&gt;] [\&lt;header-name\&gt;]'],['../commands.html#cmdstruct',1,'\\struct \&lt;name\&gt; [\&lt;header-file\&gt;] [\&lt;header-name\&gt;]'],['../commands.html#cmdunion',1,'\\union \&lt;name\&gt; [\&lt;header-file\&gt;] [\&lt;header-name\&gt;]']]],
  ['file_20menu_9',['File menu',['../doxywizard_usage.html#dw_menu_file',1,'']]],
  ['file_20name_10',['file name',['../commands.html#cmddocbookinclude',1,'\\docbookinclude &lt;file-name&gt;'],['../commands.html#cmddontinclude',1,'\\dontinclude[&apos;{lineno}&apos;] &lt;file-name&gt;'],['../commands.html#cmdexample',1,'\\example[&apos;{lineno}&apos;] \&lt;file-name\&gt;'],['../commands.html#cmdfile',1,'\\file [\&lt;name\&gt;]'],['../commands.html#cmdhtmlinclude',1,'\\htmlinclude[&apos;[block]&apos;] &lt;file-name&gt;'],['../commands.html#cmdinclude',1,'\\include[&apos;{&apos;option&apos;}&apos;] &lt;file-name&gt;'],['../commands.html#cmdincludedoc',1,'\\includedoc[&apos;{&apos;option&apos;}&apos;] &lt;file-name&gt;'],['../commands.html#cmdincludelineno',1,'\\includelineno &lt;file-name&gt;'],['../commands.html#cmdlatexinclude',1,'\\latexinclude &lt;file-name&gt;'],['../commands.html#cmdmaninclude',1,'\\maninclude &lt;file-name&gt;'],['../commands.html#cmdrtfinclude',1,'\\rtfinclude &lt;file-name&gt;'],['../commands.html#cmdverbinclude',1,'\\verbinclude &lt;file-name&gt;'],['../commands.html#cmdxmlinclude',1,'\\xmlinclude &lt;file-name&gt;']]],
  ['file_20name_20block_5fid_11',['file name block_id',['../commands.html#cmdsnippet',1,'\\snippet[&apos;{&apos;option&apos;}&apos;] &lt;file-name&gt; ( block_id )'],['../commands.html#cmdsnippetdoc',1,'\\snippetdoc[&apos;{&apos;option&apos;}&apos;] &lt;file-name&gt; ( block_id )'],['../commands.html#cmdsnippetlineno',1,'\\snippetlineno &lt;file-name&gt; ( block_id )']]],
  ['file_20namespace_20are_20not_20documented_12',['Help, some/all of the members of my class / file / namespace are not documented?',['../faq.html#fac_al',1,'']]],
  ['file_20with_20a_20custom_20extension_20is_20not_20parsed_20properly_20anymore_13',['My file with a custom extension is not parsed (properly) (anymore).',['../faq.html#faq_ext_mapping',1,'']]],
  ['fileinfo_20option_14',['\\fileinfo[&apos;{&apos;option&apos;}&apos;]',['../commands.html#cmdfileinfo',1,'']]],
  ['files_15',['Automatically Adding Files',['../additional.html#automatically_adding_files',1,'']]],
  ['files_16',['files',['../config.html#config_input',1,'Configuration options related to the input files'],['../autolink.html#linkfile',1,'Links to files']]],
  ['files_20as_20pages_17',['Including Markdown files as pages',['../markdown.html#md_page_header',1,'']]],
  ['files_20in_20combination_20with_20compressed_20html_18',['How can I use tag files in combination with compressed HTML?',['../faq.html#faq_chm',1,'']]],
  ['fine_20tuning_20the_20output_19',['Fine-tuning the output',['../doxygen_usage.html#doxygen_finetune',1,'']]],
  ['flow_20chart_20',['\\vhdlflow [(title for the flow chart)]',['../commands.html#cmdvhdlflow',1,'']]],
  ['fn_20function_20declaration_21',['\\fn (function declaration)',['../commands.html#cmdfn',1,'']]],
  ['footer_20and_20stylesheet_20changes_22',['Header, Footer, and Stylesheet changes',['../customize.html#minor_tweaks_header_css',1,'']]],
  ['for_20c_20like_20languages_20c_20c_20c_20objective_20c_20php_20java_23',['Comment blocks for C-like languages (C/C++/C#/Objective-C/PHP/Java)',['../docblocks.html#cppblock',1,'']]],
  ['for_20github_20alerts_24',['Support for GitHub Alerts',['../markdown.html#mddox_github_alerts',1,'']]],
  ['for_20the_20autogen_20definitions_20output_25',['Configuration options for the AutoGen Definitions output',['../config.html#config_autogen',1,'']]],
  ['for_20the_20flow_20chart_26',['\\vhdlflow [(title for the flow chart)]',['../commands.html#cmdvhdlflow',1,'']]],
  ['format_27',['Format',['../config.html#config_format',1,'']]],
  ['format_28',['format',['../perlmod.html#doxydocs_format',1,'Documentation format.'],['../extsearch.html#extsearch_api_index',1,'Indexer input format'],['../extsearch.html#extsearch_api_search_out',1,'Search results format'],['../extsearch.html#extsearch_api_search_in',1,'Search URL format']]],
  ['format_20date_5ftime_29',['\\showdate \&quot;\&lt;format\&gt;\&quot; [ \&lt;date_time\&gt; ]',['../commands.html#cmdshowdate',1,'']]],
  ['format_20file_20caption_20sizeindication_20size_30',['\\image[&apos;{&apos;option[,option]&apos;}&apos;] \&lt;format\&gt; \&lt;file\&gt; [&quot;caption&quot;] [\&lt;sizeindication\&gt;=\&lt;size\&gt;]',['../commands.html#cmdimage',1,'']]],
  ['formats_31',['Output Formats',['../output.html',1,'']]],
  ['formulas_32',['Including formulas',['../formulas.html',1,'']]],
  ['fortran_33',['Comment blocks in Fortran',['../docblocks.html#fortranblocks',1,'']]],
  ['fragment_34',['fragment',['../commands.html#cmddir',1,'\\dir [\&lt;path fragment\&gt;]'],['../faq.html#faq_code',1,'How can I make Doxygen ignore some code fragment?']]],
  ['frequently_20asked_20questions_35',['Frequently Asked Questions',['../faq.html',1,'']]],
  ['from_20my_20directory_20tree_36',['How can I exclude all test directories from my directory tree?',['../faq.html#faq_excl_dir',1,'']]],
  ['from_20source_20on_20unix_37',['Compiling from source on UNIX',['../install.html#install_src_unix',1,'']]],
  ['from_20source_20on_20windows_38',['Compiling from source on Windows',['../install.html#install_src_windows',1,'']]],
  ['from_20the_20command_20line_39',['Can I configure Doxygen from the command line?',['../faq.html#faq_cmdline',1,'']]],
  ['function_20declaration_40',['function declaration',['../commands.html#cmdfn',1,'\\fn (function declaration)'],['../commands.html#cmdoverload',1,'\\overload [(function declaration)]']]],
  ['functions_41',['Links to functions',['../autolink.html#linkfunc',1,'']]],
  ['functions_20are_20shown_20in_20the_20documentation_42',['When I set EXTRACT_ALL to NO none of my functions are shown in the documentation.',['../faq.html#faq_extract_all',1,'']]]
];
